### ISSUE TITLE
Propuesta 

### ISSUE THREAD

**Issue by lmf768** [ClaudiaAbgt/CalidadAulas#1]
Hola Claudia,

Estaría bien que añadieses más librerías en tu programa main.c

Un saludo.

**Comment by ClaudiaAbgt** [comment]
¿¡QUÉ DICES!?¿QUIÉN ERES!?

**Comment by ClaudiaAbgt** [comment]
Hola Lara,

nos importa tu opinión pero no lo suficiente.

Gracias, un saludo.
